//------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuangBaDuLichBaDong.Admin
{
    public partial class QuanLyBaiViet
    {
        /// <summary>
        /// hfMaBaiViet control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfMaBaiViet;

        /// <summary>
        /// txtTieuDe control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTieuDe;

        /// <summary>
        /// ddlDiaDiem control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDiaDiem;

        /// <summary>
        /// txtNoiDung control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNoiDung;

        /// <summary>
        /// btnThem control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnThem;

        /// <summary>
        /// btnLamMoi control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLamMoi;

        /// <summary>
        /// gvBaiViet control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvBaiViet;
    }
}